// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW3KR6Axd-62teFTxGdU723Puof9EG2T0',
    appId: '1:872466926408:web:eb7f0dd85ee956e450c17d',
    messagingSenderId: '872466926408',
    projectId: 'talk-wave-cf18d',
    authDomain: 'talk-wave-cf18d.firebaseapp.com',
    storageBucket: 'talk-wave-cf18d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd4_RohxK4CNEzmsWFyyzeTApwM34EVhE',
    appId: '1:872466926408:android:631570048f92be0b50c17d',
    messagingSenderId: '872466926408',
    projectId: 'talk-wave-cf18d',
    storageBucket: 'talk-wave-cf18d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-7eZW3F_wOzqrNWKTb6FEE4CRVlYdR-k',
    appId: '1:872466926408:ios:cd8f4c290ae0020f50c17d',
    messagingSenderId: '872466926408',
    projectId: 'talk-wave-cf18d',
    storageBucket: 'talk-wave-cf18d.appspot.com',
    iosClientId:
        '872466926408-mvdn7sncfka1mefkc11p2ath9gi0kg5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChatappChitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-7eZW3F_wOzqrNWKTb6FEE4CRVlYdR-k',
    appId: '1:872466926408:ios:5b4fcdd10edef96850c17d',
    messagingSenderId: '872466926408',
    projectId: 'talk-wave-cf18d',
    storageBucket: 'talk-wave-cf18d.appspot.com',
    iosClientId:
        '872466926408-ca4adnak92ld48pukakr0s444pcmlc07.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChatappChitchat.RunnerTests',
  );
}
